metadata:
  name: msadp-d-deposit-account-detail
  labels:
    app: msadp-d-deposit-account-detail
spec:
  replicas: 1
  template:
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: 'default'
            - name: JAVA_MAX_MEM_RATIO
              value: '0'
            - name: JAVA_TOOL_OPTIONS
              value:
                -XX:+UnlockExperimentalVMOptions
                -XX:+UseCGroupMemoryLimitForHeap
            - name: TZ
              value: 'America/Mexico_City'
          name: msadp-d-deposit-account-detail
          envFrom:
            - secretRef:
                name: bsi-informix-estandar-data
            - secretRef:
                name: bsi-informix-username-uno-data
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 9779
              name: prometheus
              protocol: TCP
            - containerPort: 8778
              name: jolokia
              protocol: TCP
            - containerPort: 8181
              name: actuator
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8181
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 30
            timeoutSeconds: 20
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8181
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 20
            timeoutSeconds: 20
          resources:
            limits:
              cpu: 300m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
          - name: msadp-d-deposit-account-detail-config
            mountPath: /deployments/config
      volumes:
        - name: msadp-d-deposit-account-detail-config
          configMap:
            name: msadp-d-deposit-account-detail
